"""Add MonthInfo model

Revision ID: 372c39660785
Revises: 785679004e8b
Create Date: 2024-10-22 20:12:19.775347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372c39660785'
down_revision = '785679004e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('month_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('norm_hours', sa.Float(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('night_hours', sa.Float(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('advance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month_info')
    # ### end Alembic commands ###
